edition: 1.0.0
name: hello-world-app
access: "default"

vars:
  region: "cn-hangzhou"
  service:
    name: "serverless-cd"
    description: 'serverless cd service'

services:
  helloworld:
    component: fc
    actions:
      pre-deploy:
        - component: fc build --use-docker --dockerfile ./code/Dockerfile
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "custom-nodejs14-event-function"
        description: 'hello world by serverless devs'
        caPort: 9000
        memorySize: 256
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: "https://cr.console.aliyun.com/a.acr"
        codeUri: ./code